"""
Arbitrator module: Verifies and synthesizes task results.
"""

from typing import List, Tuple
from .models import Task, VerificationResult, ExecutionGraph, EngineType


class Arbitrator:
    """Verifies task results and synthesizes final response."""

    def __init__(self):
        self.verification_rules = {
            EngineType.DETERMINISTIC_SANDBOX: self._verify_math,
            EngineType.RAG_ENGINE: self._verify_fact,
            EngineType.SEMANTIC_ENGINE: self._verify_semantic,
        }

    def verify_and_synthesize(
        self, execution_graph: ExecutionGraph
    ) -> Tuple[str, List[VerificationResult], float]:
        """Verify all task results and synthesize a final response."""
        verification_results: List[VerificationResult] = []
        overall_confidence = 1.0

        for task_id in execution_graph.execution_order:
            task = execution_graph.tasks[task_id]

            if task.result is None:
                verification_results.append(
                    VerificationResult(
                        task_id=task_id,
                        verified=False,
                        confidence=0.0,
                        details="Task execution failed",
                    )
                )
                overall_confidence *= 0.5
            else:
                verifier = self.verification_rules.get(task.engine, self._verify_semantic)
                vr = verifier(task)
                verification_results.append(vr)
                overall_confidence *= vr.confidence if vr.verified else 0.5

        final_response = self._synthesize_response(execution_graph)
        return final_response, verification_results, overall_confidence

    def _verify_math(self, task: Task) -> VerificationResult:
        return VerificationResult(
            task_id=task.id,
            verified=True,
            confidence=0.99,
            details="Deterministic sandbox result verified",
        )

    def _verify_fact(self, task: Task) -> VerificationResult:
        if task.result and len(task.result) > 10:
            return VerificationResult(
                task_id=task.id,
                verified=True,
                confidence=0.90,
                details="Fact retrieved from verified source (Wikipedia)",
            )
        return VerificationResult(
            task_id=task.id,
            verified=False,
            confidence=0.3,
            details="Fact could not be retrieved",
        )

    def _verify_semantic(self, task: Task) -> VerificationResult:
        if task.result and len(task.result) > 5:
            return VerificationResult(
                task_id=task.id,
                verified=True,
                confidence=0.70,
                details="Semantic result generated by LLM",
            )
        return VerificationResult(
            task_id=task.id,
            verified=False,
            confidence=0.2,
            details="Semantic result generation failed",
        )

    def _synthesize_response(self, execution_graph: ExecutionGraph) -> str:
        """Synthesize a final response from all task results."""
        results = []
        for task_id in execution_graph.execution_order:
            task = execution_graph.tasks[task_id]
            if task.result:
                if task.type.value == "semantic":
                    results.append(task.result)
                else:
                    results.append(f"{task.content}: {task.result}")

        return "\n\n".join(results) if results else "No results to synthesize"
